name: Call Vercel Cron Endpoint

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes
  workflow_dispatch:

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel endpoint
        env:
          SECRET: ${{ secrets.CRON_SECRET }}
        run: curl -s "https://news-headline-fetch.vercel.app/cron?secret=$SECRET"
